language: python

sudo: false

python:
  - 3.7
  - 3.8
  - 3.9

addons:
  apt:
    packages:
    - iverilog

install:
  - pip install pytest pytest-pythonpath jinja2 ply

script:
  - python -m pytest tests
