name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: install verilog simulator
        run: |
          sudo apt-get update
          sudo apt-get install iverilog
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
