name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: iverilog
          version: 1.0
          execute_install_scripts: true
#       - name: Install verilog simulator
#         if: steps.cache-apt.outputs.cache-hit != 'true'
#         run: |
#           sudo apt-get update
#           sudo apt-get install iverilog
      
      - uses: education/autograding@v1
